optional configids seems wrong, maybe random is better?
tlswg/draft-ietf-tls-esni pull request #495
Opened 2021-08-05 00:14 UTC by sftcd

minor suggested change

2021-08-05 21:50 UTC, chris-wood requested changes

2021-08-05 21:50 UTC, chris-wood commented on draft-ietf-tls-esni.md
> +the second ClientHelloOuter.
The intent was to say that optional IDs are to be implemented as random IDs, i.e., if you don't care about IDs (hence optional), then just set them to a random byte. So I'm not inclined to take this change.

I _do_ like the clarification to include "in the event of HRR" -- can we split that out into a separate PR?

2021-08-06 00:07 UTC, sftcd commented
Hiya,

On 05/08/2021 22:50, Christopher Wood wrote:
> @chris-wood requested changes on this pull request.
> 
> 
> 
>> `config_id` SHOULD be set to a randomly generated byte in the
>> first
> -ClientHelloOuter and MUST be left unchanged for the second
> ClientHelloOuter. +ClientHelloOuter and, in the event of HRR, MUST be
> left unchanged for +the second ClientHelloOuter.
> 
> The intent was to say that optional IDs are to be implemented as
> random IDs, i.e., if you don't care about IDs (hence optional), 

For me, for a protocol element, "optional" means "not
included" whereas here we're talking about "optionally
ignoring the proposed value." (Yeah, I probably read
too much ASN.1 once, or even twice:-)

"Random" might not be right, but "optional" could maybe
briefly confuse an implementer.

> then
> just set them to a random byte. So I'm not inclined to take this
> change.
> 
> I _do_ like the clarification to include "in the event of HRR" -- can
> we split that out into a separate PR?

Sure. (Not that I know how to do that easily, but feel free
to just do it, or wait for me to figure it out tomorrow;-)

Cheers,
S.


>

2021-08-06 03:28 UTC, cbartle891 commented
> For me, for a protocol element, "optional" means "not
> included" whereas here we're talking about "optionally
> ignoring the proposed value."

I agree.

2021-08-06 12:45 UTC, chris-wood commented
It's not possible to omit the config ID (it's a byte). It's only possible to not use it. Optional seems like a fine word to capture that. We could also say that it's unused or ignored? For example:

```
If `config_id` is unused as specified by an application profile or otherwise 
externally configured, `config_id` SHOULD be set to a randomly generated byte
in the first ClientHelloOuter and, in the event of HRR, MUST be left unchanged
for the second ClientHelloOuter.
```

Or something, with similar updates to the text and section titles. Would that work?

2021-08-06 13:02 UTC, sftcd commented
On 06/08/2021 13:45, Christopher Wood wrote:
> It's not possible to omit the config ID (it's a byte). It's only
> possible to not use it. Optional seems like a fine word to capture
> that.

Interesting, (but unimportant:-) my take on those facts
is the opposite.

> We could also say that it's unused or ignored? For example:
> 
> ``` If `config_id` is unused as specified by an application profile
> or otherwise externally configured, `config_id` SHOULD be set to a
> randomly generated byte in the first ClientHelloOuter and, in the
> event of HRR, MUST be left unchanged for the second
> ClientHelloOuter. ```
> 
> Or something, with similar updates to the text and section titles.
> Would that work?

For me: "ignored" is ok, "unused" is as odd as "optional."

Cheers,
S.

2021-08-06 16:17 UTC, chris-wood commented
@sftcd updated the proposal above to use "ignored". Does that work?

2021-08-06 16:18 UTC, sftcd commented
On 06/08/2021 17:17, Christopher Wood wrote:
> @sftcd updated the proposal above to use "ignored". Does that work?

Sure. Thanks,
S

>

2021-08-06 16:43 UTC, chris-wood commented
Great! Could you please update this PR to match?

2021-08-09 15:48 UTC, sftcd commented
I think I've made those changes now.

2021-08-09 17:19 UTC, chris-wood approved these changes

2021-08-09 17:21 UTC, chris-wood commented on draft-ietf-tls-esni.md
> +ClientHelloOuter and, in the event of HRR, MUST be left unchanged for
```suggestion
ClientHelloOuter and, in the event of HRR, MUST be left unchanged for
```

2021-08-09 17:23 UTC, chris-wood commented on draft-ietf-tls-esni.md
> +Unless specified by the application using (D)TLS or externally configured,
```suggestion
Unless specified by the application using (D)TLS or externally configured,
```

2021-08-09 17:24 UTC, merged